package com.jastin.boveda.database

import app.cash.sqldelight.db.SqlDriver
import app.cash.sqldelight.driver.native.NativeSqliteDriver

/* =========================================================================
 * DRIVER IMPLEMENTATION (IOS / NATIVE)
 * Provides the specific SQLite engine for the Apple native environment.
 * ========================================================================= */

actual class DatabaseDriverFactory {

    // --- 1. NATIVE ENGINE CONFIGURATION ---
    // Unlike Android, iOS does not require a 'Context' to access
    // the local file system. We access Apple's SQLite APIs directly
    // via 'NativeSqliteDriver'.
    actual fun createDriver(): SqlDriver {
        // NOTE: 'BovedaDatabase.Schema' is automatically generated by SQLDelight.
        // If you modify the .sq file, the driver will handle database migrations
        // atomically on the first app access.
        return NativeSqliteDriver(BovedaDatabase.Schema, "boveda_local.db")
    }
}