name: KMP Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
 
    runs-on: macos-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Configurar Java (JDK 17)
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Configurar Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Dar permisos de ejecución a Gradle
      run: chmod +x gradlew

    - name: Compilar Proyecto (Android e iOS)
    
      run: ./gradlew build --no-daemon
